### ISSUE TITLE
Vapoursynth C++ port

### ISSUE THREAD

**Issue by End-of-Eternity** [DomBito/VapourSynth-CCD#1]
Just letting you know that I have now ported this function to a Vapoursynth plugin [here](https://github.com/End-of-Eternity/vs-ccd). Your description of how the filter worked was especially useful in helping my understanding, thanks very much! I would like to add that description to the new repo, if that's okay with you? Cheers :)

**Comment by End-of-Eternity** [comment]
Oh also, I was wondering where [this](https://github.com/DomBito/VapourSynth-CCD/blob/main/ccd.py#L42) "magic number" came from.

**Comment by DomBito** [comment]
Hello, @End-of-Eternity. Thank you so much for implementing the CCD in C++. I have tested my own script on HD and 4K footage by scaling up the kernel without adding more pixels to it (just making it 4 or 16 times larger and more sparse), and the results are great. I don't know you did this adjustments to work on higher resolutions, but I strongly recommend it, since CCD doesn't work well on HD as it is.

About the modified threshold number. This number works on squares of the distance between normalized RGB values. But working directly on normalized RGB would make the user input really small floating points. So I'm bringing the user back to the 8-bit scale and normalizing their imput by the square of the Euclidian diameter of the 8-bit RGB cube, which is 3*255².

Also, feel free to add my description to your repo.

**Comment by End-of-Eternity** [comment]
Re: HD+. that sounds like a pretty good idea - prehaps calculating the matrix size + offsets based on the full frame size would be a good addition to CCD. I'm also working on an implementation that picks 16 random points within the full matrix, instead of constant offsets, to try to negate issues with "ghosting" type artifacts. I think there's a lot of experimentation to be done with the base concept.

Re: the magic number, I had assumed as much, I was just struggling to get your exact number with my calculations. Thanks for making it more obvious :)

I will add your description to the repo later today then. Feel free to create an issue on the new repo if you have any further thoughts about what should be implemented, and what else can be tried. Many thanks, EoE
